# Generated by Django 4.2.25 on 2025-10-09 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerieReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Clase de Redes - Semestre Otoño 2025', max_length=200)),
                ('profesor', models.CharField(blank=True, max_length=100)),
                ('materia', models.CharField(blank=True, max_length=100)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.laboratorio')),
            ],
            options={
                'verbose_name': 'Serie de Reserva',
                'verbose_name_plural': 'Series de Reservas',
            },
        ),
        migrations.AddField(
            model_name='reservaclase',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocurrencias', to='gestion.seriereserva'),
        ),
    ]
