# Generated by Django 4.2.25 on 2025-10-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_seriereserva_reservaclase_serie'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('periodo', models.CharField(choices=[('semanal', 'Semanal'), ('mensual', 'Mensual'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('incluir_graficos', models.BooleanField(default=True)),
                ('incluir_tablas', models.BooleanField(default=True)),
                ('incluir_estadisticas', models.BooleanField(default=True)),
                ('creado_por', models.CharField(blank=True, max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Configuración de Reporte',
                'verbose_name_plural': 'Configuraciones de Reportes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
