# Generated by Django 4.2.25 on 2025-10-17 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_configuracionreporte'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracionReporte',
        ),
    ]
