# Generated by Django 4.2.25 on 2025-10-20 19:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_delete_configuracionreporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriereserva',
            name='activa',
            field=models.BooleanField(default=True, help_text='Si la serie está activa'),
        ),
        migrations.AddField(
            model_name='seriereserva',
            name='creada_el',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seriereserva',
            name='dias_semana',
            field=models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('X', 'Miércoles'), ('J', 'Jueves'), ('V', 'Viernes'), ('S', 'Sábado'), ('D', 'Domingo')], default='LMXJV', help_text='Selecciona los días de la semana (ej: LMXJV)', max_length=7),
        ),
        migrations.AddField(
            model_name='seriereserva',
            name='fecha_fin',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha de fin de la serie de reservas'),
        ),
        migrations.AddField(
            model_name='seriereserva',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha de inicio de la serie de reservas'),
        ),
        migrations.AddField(
            model_name='seriereserva',
            name='hora_fin',
            field=models.TimeField(default='09:00', help_text='Hora de fin (ej: 09:00)'),
        ),
        migrations.AddField(
            model_name='seriereserva',
            name='hora_inicio',
            field=models.TimeField(default='08:00', help_text='Hora de inicio (ej: 08:00)'),
        ),
    ]
