# Generated by Django 4.2.25 on 2025-10-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_seriereserva_activa_seriereserva_creada_el_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=1, unique=True)),
                ('nombre', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Día de la Semana',
                'verbose_name_plural': 'Días de la Semana',
            },
        ),
        migrations.RemoveField(
            model_name='seriereserva',
            name='dias_semana',
        ),
        migrations.AddField(
            model_name='seriereserva',
            name='dias_semana',
            field=models.ManyToManyField(help_text='Selecciona los días de la semana', to='gestion.diasemana'),
        ),
    ]
