# Generated by Django 4.2.25 on 2025-10-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_diasemana_remove_seriereserva_dias_semana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('En Uso', 'En Uso'), ('Mantenimiento', 'Mantenimiento'), ('Reservada', 'Reservada')], default='Disponible', max_length=20),
        ),
    ]
