# Generated by Django 4.2.25 on 2025-11-21 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_pc_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diasemana',
            options={'ordering': ['codigo'], 'verbose_name': 'Día de la Semana', 'verbose_name_plural': 'Días de la Semana'},
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del mantenimiento', null=True)),
                ('fecha_inicio', models.DateTimeField(help_text='Fecha y hora de inicio del mantenimiento')),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Fecha y hora de fin del mantenimiento', null=True)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='gestion.pc')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
