# Generated by Django 4.2.7 on 2026-02-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_diasemana_options_mantenimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'verbose_name': 'Visitante', 'verbose_name_plural': 'Visitantes'},
        ),
        migrations.AlterModelOptions(
            name='laboratorio',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='seriereserva',
            name='color',
            field=models.CharField(default='#667eea', help_text='Color en formato hexadecimal (ej: #FF5733)', max_length=7),
        ),
    ]
