# Generated by Django 4.2.7 on 2026-02-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_estudiante_options_alter_laboratorio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaclase',
            name='color',
            field=models.CharField(blank=True, default='#667eea', help_text='Color en formato hexadecimal (ej: #FF5733). Si está vacío, usa el color de la serie.', max_length=7, null=True),
        ),
    ]
