# Generated by Django 4.2.7 on 2026-02-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_reservaclase_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaclase',
            name='carrera',
            field=models.CharField(blank=True, help_text='Nombre de la carrera', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reservaclase',
            name='numero_alumnos',
            field=models.IntegerField(blank=True, help_text='Número de alumnos', null=True),
        ),
        migrations.AddField(
            model_name='reservaclase',
            name='semestre',
            field=models.IntegerField(blank=True, help_text='Semestre (número entero)', null=True),
        ),
        migrations.AddField(
            model_name='seriereserva',
            name='carrera',
            field=models.CharField(blank=True, help_text='Nombre de la carrera (ej: Ingeniería en Sistemas)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='seriereserva',
            name='numero_alumnos',
            field=models.IntegerField(blank=True, help_text='Número de alumnos en la clase', null=True),
        ),
        migrations.AddField(
            model_name='seriereserva',
            name='semestre',
            field=models.IntegerField(blank=True, help_text='Semestre (número entero, ej: 3)', null=True),
        ),
    ]
