# Generated by Django 4.2.7 on 2026-02-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_reservaclase_carrera_reservaclase_numero_alumnos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='carrera',
            field=models.CharField(blank=True, help_text='Carrera del estudiante', max_length=200, null=True),
        ),
    ]
