# Generated by Django 4.2.7 on 2026-02-06 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_estudiante_carrera'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionActiva',
            fields=[
            ],
            options={
                'verbose_name': 'Sesión Activa',
                'verbose_name_plural': 'Sesiones Activas',
                'permissions': [('can_view_sesiones_activas', 'Puede ver sesiones activas'), ('can_finalizar_sesiones', 'Puede finalizar sesiones')],
                'proxy': True,
                'default_permissions': ('view', 'delete'),
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.visita',),
        ),
    ]
