# Generated by Django 4.2.7 on 2026-02-06 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_sesionactiva'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioSemanal',
            fields=[
            ],
            options={
                'verbose_name': 'Calendario Semanal',
                'verbose_name_plural': '📅 Calendario Semanal',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gestion.reservaclase',),
        ),
    ]
