# Generated by Django 4.2.7 on 2026-02-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_calendariosemanal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='calendariosemanal',
            options={'verbose_name': 'Calendario Semanal', 'verbose_name_plural': 'Calendario Semanal'},
        ),
        migrations.AddField(
            model_name='reservaclase',
            name='nota',
            field=models.TextField(blank=True, help_text='Nota visible en el calendario (ej: Examen, Curso, Evento). Solo para reservas individuales.', null=True),
        ),
    ]
