# Generated by Django 4.2.7 on 2026-03-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_add_carrera_model_and_nota_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaclase',
            name='tipo_evento',
            field=models.CharField(choices=[('clase', 'Clase'), ('examen', 'Examen'), ('conferencia', 'Conferencia'), ('taller', 'Taller'), ('otro', 'Otro')], default='clase', help_text='Tipo de evento que ocupa el laboratorio', max_length=20),
        ),
    ]
