# Generated by Django 4.2.7 on 2026-03-05 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_add_tipo_evento_to_reservaclase'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#667eea', help_text='Color del badge en formato hex (ej: #FF5733)', max_length=7)),
            ],
            options={
                'verbose_name': 'Tipo de Evento',
                'verbose_name_plural': 'Tipos de Evento',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='seriereserva',
            name='tipo_evento',
            field=models.ForeignKey(blank=True, help_text='Tipo de evento de la serie (Clase, Examen, Conferencia…)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series', to='gestion.tipoevento'),
        ),
        migrations.RemoveField(
            model_name='reservaclase',
            name='tipo_evento',
        ),
        migrations.AddField(
            model_name='reservaclase',
            name='tipo_evento',
            field=models.ForeignKey(blank=True, help_text='Tipo de evento que ocupa el laboratorio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='gestion.tipoevento'),
        ),
    ]
