# Generated by Django 4.2.7 on 2026-03-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_add_tipo_evento_model_and_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='activo',
            field=models.BooleanField(default=True, help_text='Desmarcar para excluir este laboratorio de las estadísticas y del calendario de reservas.'),
        ),
    ]
